# Blog details (rendered in the header)
title: UTF-9000
description: My Open Source Jekyll theme

# Pathing information
baseurl: ""
url: ""

# Contact details (for the footer)
email: user@example.com
# linkedin:
# steam:
# twitter:
# github:

# Build settings
destination: docs
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
